// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcktcwjybbdbofbqftdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indja3Rjd2p5YmJkYm9mYnFmdGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDM1MzgsImV4cCI6MjA1OTUxOTUzOH0.4NAoDo8cYtjjvgY_uPdrLCyAn55SmIeNPPGlkLDljAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);